# Generated by Django 5.2.17 on 2026-08-15 07:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=200)),
                ('alert_type', models.CharField(choices=[('POS_UNACK', 'A positive infant result has not been acknowledged'), ('LINK_OVERDUE', 'A positive infant has not started treatment'), ('EID_DUE', 'An infant test appointment falls due'), ('EID_MISSED', 'An infant test appointment was missed'), ('SAMPLE_OVERDUE', 'A sample has been at the laboratory too long'), ('VISIT_MISSED', 'A planned home visit did not happen'), ('LTFU_RISK', 'A client has had no contact for some time'), ('VISIT_FLAG', 'A visit needs supervisor review'), ('SYNC_BACKLOG', 'A handset has not synchronised')], max_length=16, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=8)),
                ('threshold_value', models.IntegerField(help_text='Meaning depends on the rule: days overdue, hours elapsed, count.')),
                ('threshold_unit', models.CharField(choices=[('HOURS', 'Hours'), ('DAYS', 'Days'), ('COUNT', 'Count')], default='DAYS', max_length=10)),
                ('notify_mentor_mother', models.BooleanField(default=False)),
                ('notify_facility_supervisor', models.BooleanField(default=True)),
                ('notify_lga_coordinator', models.BooleanField(default=False)),
                ('send_sms', models.BooleanField(default=False)),
                ('sms_template_key', models.CharField(blank=True, max_length=40)),
                ('escalate_after_hours', models.PositiveIntegerField(blank=True, help_text='Hours without acknowledgement before the alert goes one tier up.', null=True)),
            ],
            options={
                'ordering': ['alert_type'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=200)),
                ('alert_type', models.CharField(choices=[('POS_UNACK', 'A positive infant result has not been acknowledged'), ('LINK_OVERDUE', 'A positive infant has not started treatment'), ('EID_DUE', 'An infant test appointment falls due'), ('EID_MISSED', 'An infant test appointment was missed'), ('SAMPLE_OVERDUE', 'A sample has been at the laboratory too long'), ('VISIT_MISSED', 'A planned home visit did not happen'), ('LTFU_RISK', 'A client has had no contact for some time'), ('VISIT_FLAG', 'A visit needs supervisor review'), ('SYNC_BACKLOG', 'A handset has not synchronised')], db_index=True, max_length=16)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], db_index=True, max_length=8)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved'), ('ESCALATED', 'Escalated'), ('CANCELLED', 'No longer applicable')], db_index=True, default='OPEN', max_length=12)),
                ('subject_type', models.CharField(help_text='Model label, for example registry.Infant.', max_length=40)),
                ('subject_id', models.UUIDField()),
                ('deduplication_key', models.CharField(db_index=True, max_length=200, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('detail', models.TextField(blank=True)),
                ('raised_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('acknowledge_by', models.DateTimeField(db_index=True, help_text='Deadline. Set from the severity.')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgement_channel', models.CharField(blank=True, choices=[('APP', 'In the application'), ('SMS', 'By SMS reply')], max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('escalation_level', models.PositiveSmallIntegerField(default=0, help_text='0 means not escalated. Each step raises the tier.')),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('assigned_mentor_mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to='registry.mentormother')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='registry.facility')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='alerts.alertrule')),
            ],
            options={
                'ordering': ['-severity', 'acknowledge_by'],
            },
        ),
        migrations.CreateModel(
            name='AlertEscalation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=200)),
                ('level', models.PositiveSmallIntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='alerts.alert')),
                ('escalated_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalations_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['alert', 'level'],
                'unique_together': {('alert', 'level')},
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', 'acknowledge_by'], name='alerts_aler_status_16ad00_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['facility', 'status', 'severity'], name='alerts_aler_facilit_dbc350_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['subject_type', 'subject_id'], name='alerts_aler_subject_0ae123_idx'),
        ),
    ]
