# Generated by Django 5.2.17 on 2026-08-15 07:58

import apps.common.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=200)),
                ('key', models.CharField(help_text='Referenced by an alert rule, for example eid_due.', max_length=40)),
                ('language', models.CharField(choices=[('en', 'English'), ('ha', 'Hausa'), ('yo', 'Yoruba'), ('ig', 'Igbo'), ('pcm', 'Nigerian Pidgin')], default='en', max_length=4)),
                ('body', models.TextField(help_text='Use {baby_code}, {client_code}, {staff_code}, {due_date_words}. A placeholder that would insert a name is rejected.', max_length=320)),
                ('expects_reply', models.BooleanField(default=False)),
                ('reply_keywords', models.JSONField(blank=True, default=list, help_text='Accepted replies, for example ["DONE", "SEEN", "NO"].')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['key', 'language'],
                'unique_together': {('key', 'language')},
            },
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=200)),
                ('recipient_kind', models.CharField(choices=[('MENTOR_MOTHER', 'Mentor mother'), ('CLIENT', 'Client'), ('SUPERVISOR', 'Facility supervisor')], max_length=16)),
                ('recipient_msisdn', apps.common.fields.EncryptedCharField(max_length=20)),
                ('recipient_reference', models.CharField(blank=True, help_text='Staff code or client code of the recipient. Never a name.', max_length=24)),
                ('template_key', models.CharField(max_length=40)),
                ('render_arguments', models.JSONField(blank=True, default=dict)),
                ('body_length', models.PositiveSmallIntegerField(default=0)),
                ('segment_count', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Handed to the gateway'), ('DELIVERED', 'Delivered to the handset'), ('FAILED', 'Delivery failed'), ('BLOCKED', 'Blocked by the privacy guard'), ('EXPIRED', 'The gateway gave up')], db_index=True, default='QUEUED', max_length=10)),
                ('guard_violations', models.JSONField(blank=True, default=list, help_text='Populated when the privacy guard blocked the message.')),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('provider_status_detail', models.CharField(blank=True, max_length=200)),
                ('cost_naira', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('expects_reply', models.BooleanField(default=False)),
                ('reply_received_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='alerts.alert')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='registry.facility')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='messaging.messagetemplate')),
            ],
            options={
                'ordering': ['-queued_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=200)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sender_msisdn', apps.common.fields.EncryptedCharField(max_length=20)),
                ('raw_body', models.CharField(help_text='Held in clear. A reply is a keyword and a code, and no message sent by this system ever invites a person to type an identifier.', max_length=320)),
                ('parse_status', models.CharField(choices=[('MATCHED', 'Parsed and linked to a message'), ('UNMATCHED', 'Parsed but no matching message was found'), ('UNPARSED', 'The reply could not be interpreted'), ('IGNORED', 'Not a programme reply')], db_index=True, default='UNPARSED', max_length=10)),
                ('parsed_keyword', models.CharField(blank=True, max_length=20)),
                ('parsed_code', models.CharField(blank=True, max_length=24)),
                ('action_taken', models.CharField(blank=True, help_text='What the reply caused, for example an alert acknowledgement.', max_length=120)),
                ('provider_message_id', models.CharField(blank=True, max_length=80)),
                ('matched_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_replies', to='alerts.alert')),
                ('mentor_mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_replies', to='registry.mentormother')),
                ('matched_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='messaging.outboundmessage')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=200)),
                ('provider_message_id', models.CharField(db_index=True, max_length=80)),
                ('provider_status', models.CharField(max_length=40)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_reports', to='messaging.outboundmessage')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='outboundmessage',
            index=models.Index(fields=['status', 'queued_at'], name='messaging_o_status_d30831_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundmessage',
            index=models.Index(fields=['facility', 'status'], name='messaging_o_facilit_f4fcab_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundmessage',
            index=models.Index(fields=['expects_reply', 'reply_received_at'], name='messaging_o_expects_8463f3_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundmessage',
            index=models.Index(fields=['parse_status', 'received_at'], name='messaging_i_parse_s_4ede3f_idx'),
        ),
    ]
