# Generated by Django 5.2.17 on 2026-08-15 07:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EidAppointment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=200)),
                ('milestone', models.CharField(choices=[('BIRTH', 'At birth'), ('WEEK_6', 'Six weeks'), ('MONTH_9', 'Nine months'), ('MONTH_18', 'Eighteen months'), ('UNSCHEDULED', 'Unscheduled or repeat test')], max_length=12)),
                ('due_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ATTENDED', 'Attended, sample collected'), ('MISSED', 'Missed'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=12)),
                ('attended_date', models.DateField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.PositiveSmallIntegerField(default=0)),
                ('infant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eid_appointments', to='registry.infant')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='EidSample',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=200)),
                ('sample_identifier', models.CharField(max_length=40, unique=True)),
                ('collected_on', models.DateField(db_index=True)),
                ('dispatched_on', models.DateField(blank=True, null=True)),
                ('laboratory_received_on', models.DateField(blank=True, null=True)),
                ('result_issued_on', models.DateField(blank=True, help_text='Date the laboratory issued the result.', null=True)),
                ('result_entered_at', models.DateTimeField(blank=True, db_index=True, help_text='Time a supervisor entered the result in this system.', null=True)),
                ('result_acknowledged_at', models.DateTimeField(blank=True, db_index=True, help_text='Time a supervisor confirmed the result and started acting on it. The gap from entry to acknowledgement is the relay delay.', null=True)),
                ('caregiver_informed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(choices=[('NEGATIVE', 'HIV not detected'), ('POSITIVE', 'HIV detected'), ('INDETERMINATE', 'Indeterminate, repeat required'), ('REJECTED', 'Sample rejected by the laboratory'), ('PENDING', 'Awaiting a result')], db_index=True, default='PENDING', max_length=14)),
                ('laboratory_name', models.CharField(blank=True, max_length=120)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acknowledged_samples', to=settings.AUTH_USER_MODEL)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sample', to='eid.eidappointment')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entered_samples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-collected_on'],
            },
        ),
        migrations.CreateModel(
            name='ArtLinkage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Not yet started'), ('STARTED', 'Treatment started'), ('REFUSED', 'Caregiver declined'), ('UNREACHABLE', 'Caregiver could not be reached'), ('TRANSFERRED', 'Referred to another facility'), ('DECEASED', 'Infant died before starting treatment')], db_index=True, default='PENDING', max_length=12)),
                ('art_start_date', models.DateField(blank=True, db_index=True, null=True)),
                ('regimen', models.CharField(blank=True, max_length=80)),
                ('barrier_note', models.TextField(blank=True, help_text='Why linkage has not happened. Read at the monthly review.')),
                ('infant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='art_linkage', to='registry.infant')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_linkages', to=settings.AUTH_USER_MODEL)),
                ('treating_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='art_linkages', to='registry.facility')),
                ('triggering_sample', models.ForeignKey(help_text='The positive result that started this linkage.', on_delete=django.db.models.deletion.PROTECT, related_name='linkages', to='eid.eidsample')),
            ],
            options={
                'verbose_name': 'ART linkage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='eidappointment',
            index=models.Index(fields=['status', 'due_date'], name='eid_eidappo_status_b83414_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eidappointment',
            unique_together={('infant', 'milestone')},
        ),
        migrations.AddIndex(
            model_name='eidsample',
            index=models.Index(fields=['result', 'result_entered_at'], name='eid_eidsamp_result_f2541e_idx'),
        ),
        migrations.AddIndex(
            model_name='eidsample',
            index=models.Index(fields=['result', 'result_acknowledged_at'], name='eid_eidsamp_result_7a1ee2_idx'),
        ),
    ]
