# Generated by Django 5.2.17 on 2026-08-15 07:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('DRY_RUN', 'Dry run, nothing was changed')], max_length=10)),
                ('policy_name', models.CharField(max_length=80)),
                ('records_examined', models.PositiveIntegerField(default=0)),
                ('records_anonymised', models.PositiveIntegerField(default=0)),
                ('records_purged', models.PositiveIntegerField(default=0)),
                ('error_detail', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_username', models.CharField(blank=True, help_text='Copied at write time, so the record survives a renamed account.', max_length=150)),
                ('actor_role', models.CharField(blank=True, max_length=24)),
                ('action', models.CharField(choices=[('CREATE', 'Created a record'), ('READ', 'Read a record'), ('UPDATE', 'Changed a record'), ('SOFT_DELETE', 'Marked a record as removed'), ('EXPORT', 'Exported data'), ('LOGIN', 'Signed in'), ('LOGIN_FAILED', 'Sign in failed'), ('LOGOUT', 'Signed out'), ('PERMISSION_DENIED', 'Access was refused'), ('CONFIG_CHANGE', 'Changed a rule or a threshold'), ('IDENTIFIER_REVEALED', 'Read a name, number or address')], db_index=True, max_length=20)),
                ('classification', models.CharField(choices=[('T1', 'Tier 1, direct identifier'), ('T2', 'Tier 2, clinical data'), ('T3', 'Tier 3, programme data'), ('T4', 'Tier 4, operational data'), ('T5', 'Tier 5, non-sensitive')], db_index=True, max_length=2)),
                ('object_type', models.CharField(blank=True, db_index=True, max_length=60)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('object_reference', models.CharField(blank=True, help_text='Programme code of the subject, for example a Baby Code.', max_length=40)),
                ('fields_touched', models.JSONField(blank=True, default=list, help_text='Field names only. Never the values held in those fields.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('request_path', models.CharField(blank=True, max_length=200)),
                ('request_method', models.CharField(blank=True, max_length=8)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('justification', models.CharField(blank=True, help_text='Required when a user reads a record outside their usual caseload.', max_length=200)),
                ('archived_to_s3', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['actor', 'occurred_at'], name='audit_audit_actor_i_50d0aa_idx'), models.Index(fields=['object_type', 'object_id', 'occurred_at'], name='audit_audit_object__6f7f8a_idx'), models.Index(fields=['action', 'classification', 'occurred_at'], name='audit_audit_action_5f3216_idx')],
            },
        ),
    ]
