# Generated by Django 5.2.17 on 2026-08-15 07:58

import apps.common.fields
import apps.registry.models
import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalGovernmentArea',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=12, unique=True)),
                ('is_pilot_site', models.BooleanField(default=False)),
                ('is_reserve_site', models.BooleanField(default=False, help_text='True for an area held in reserve. A reserve area replaces a primary area that withdraws or fails the readiness check.')),
            ],
            options={
                'ordering': ['state__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('is_pilot_site', models.BooleanField(default=False, help_text='True for a state included in the current pilot.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(help_text='National health facility code.', max_length=20, unique=True)),
                ('level', models.CharField(choices=[('PRIMARY', 'Primary health centre'), ('SECONDARY', 'Secondary, general hospital'), ('TERTIARY', 'Tertiary, teaching hospital')], max_length=12)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_pilot_site', models.BooleanField(default=False)),
                ('pilot_activation_date', models.DateField(blank=True, null=True)),
                ('has_pmtct_service', models.BooleanField(default=True)),
                ('has_eid_sample_point', models.BooleanField(default=False)),
                ('has_mobile_network_coverage', models.BooleanField(default=True)),
                ('has_signed_mou', models.BooleanField(default=False)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='registry.localgovernmentarea')),
            ],
            options={
                'verbose_name_plural': 'facilities',
                'ordering': ['lga__state__name', 'lga__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MentorMother',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=200)),
                ('staff_code', models.CharField(help_text='Programme identifier. Used in every report and every SMS.', max_length=20, unique=True)),
                ('full_name', apps.common.fields.EncryptedCharField(max_length=120)),
                ('phone_number', apps.common.fields.EncryptedCharField(help_text='Encrypted at rest.', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a Nigerian mobile number in the form +2348012345678.', regex='^\\+234[789][01]\\d{8}$')])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On leave'), ('EXITED', 'Exited the programme')], default='ACTIVE', max_length=10)),
                ('date_engaged', models.DateField(default=datetime.date.today)),
                ('date_exited', models.DateField(blank=True, null=True)),
                ('has_smartphone', models.BooleanField(default=True, help_text='False means this mentor mother works by SMS only. The alert engine sends her a structured message and parses her reply.')),
                ('training_completed_at', models.DateField(blank=True, null=True)),
                ('training_score_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mentor_mothers', to='registry.facility')),
                ('user', models.OneToOneField(blank=True, help_text='Login account. Empty for a mentor mother who works by SMS only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_mother_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['staff_code'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=200)),
                ('client_code', models.CharField(help_text='Programme identifier. Safe to use in reports and dashboards.', max_length=24, unique=True)),
                ('hospital_number', apps.common.fields.EncryptedCharField(blank=True, max_length=40)),
                ('full_name', apps.common.fields.EncryptedCharField(max_length=120)),
                ('phone_number', apps.common.fields.EncryptedCharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a Nigerian mobile number in the form +2348012345678.', regex='^\\+234[789][01]\\d{8}$')])),
                ('alternate_phone_number', apps.common.fields.EncryptedCharField(blank=True, max_length=20)),
                ('household_address', apps.common.fields.EncryptedTextField(blank=True)),
                ('household_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('household_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('year_of_birth', models.PositiveSmallIntegerField(blank=True, help_text='Year only. A full date of birth adds re-identification risk and the programme does not need it.', null=True, validators=[django.core.validators.MinValueValidator(1930)])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active in care'), ('TRANSFERRED', 'Transferred out'), ('LTFU', 'Lost to follow up'), ('EXITED', 'Exited, programme complete'), ('DECEASED', 'Deceased')], db_index=True, default='ACTIVE', max_length=12)),
                ('pregnancy_stage', models.CharField(choices=[('ANC', 'Antenatal'), ('LABOUR', 'In labour or delivery'), ('PNC', 'Postnatal'), ('NONE', 'Not currently pregnant')], default='ANC', max_length=8)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('art_start_date', models.DateField(blank=True, null=True)),
                ('date_enrolled', models.DateField(default=datetime.date.today)),
                ('date_exited', models.DateField(blank=True, null=True)),
                ('consent_given_at', models.DateTimeField(blank=True, help_text='Time the signed consent form was recorded. No consent, no digital record.', null=True)),
                ('consent_form_reference', models.CharField(blank=True, max_length=60)),
                ('sms_contact_permitted', models.BooleanField(default=False, help_text='The client agreed to receive SMS. A client may join the programme and refuse SMS contact.')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='registry.facility')),
                ('mentor_mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='registry.mentormother')),
            ],
            options={
                'ordering': ['client_code'],
            },
        ),
        migrations.AddField(
            model_name='localgovernmentarea',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lgas', to='registry.state'),
        ),
        migrations.CreateModel(
            name='Infant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=200)),
                ('baby_code', models.CharField(default=apps.registry.models.generate_baby_code, help_text='The only identifier permitted in an SMS. Random, not sequential.', max_length=12, unique=True)),
                ('given_name', apps.common.fields.EncryptedCharField(blank=True, max_length=80)),
                ('date_of_birth', models.DateField(db_index=True)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('birth_weight_grams', models.PositiveIntegerField(blank=True, null=True)),
                ('received_nevirapine_prophylaxis', models.BooleanField(blank=True, null=True)),
                ('prophylaxis_start_date', models.DateField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('IN_FOLLOW_UP', 'In follow up'), ('NEG_DISCHARGED', 'HIV negative, discharged'), ('POS_ON_ART', 'HIV positive, on treatment'), ('POS_NOT_LINKED', 'HIV positive, not yet on treatment'), ('LTFU', 'Lost to follow up'), ('TRANSFERRED', 'Transferred out'), ('DECEASED', 'Deceased')], db_index=True, default='IN_FOLLOW_UP', max_length=16)),
                ('outcome_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='infants', to='registry.facility')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='infants', to='registry.client')),
            ],
            options={
                'ordering': ['-date_of_birth'],
                'indexes': [models.Index(fields=['facility', 'outcome'], name='registry_in_facilit_da07b4_idx'), models.Index(fields=['date_of_birth', 'outcome'], name='registry_in_date_of_345961_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['facility', 'status'], name='registry_cl_facilit_da8684_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['mentor_mother', 'status'], name='registry_cl_mentor__783e0b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='localgovernmentarea',
            unique_together={('state', 'name')},
        ),
    ]
