# Generated by Django 5.2.17 on 2026-08-15 07:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeVisit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=200)),
                ('device_id', models.CharField(blank=True, help_text='Installation identifier of the handset that created the record.', max_length=64)),
                ('client_created_at', models.DateTimeField(blank=True, db_index=True, help_text='Time recorded on the handset. Use this for programme reports.', null=True)),
                ('server_received_at', models.DateTimeField(blank=True, db_index=True, help_text='Time the record reached the server.', null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('purpose', models.CharField(choices=[('ROUTINE', 'Routine support visit'), ('MISSED_APPT', 'Follow up on a missed appointment'), ('EID_REMINDER', 'Reminder of an infant test appointment'), ('ART_LINKAGE', 'Support linkage of an infant to treatment'), ('TRACING', 'Trace a client who has stopped attending'), ('POSTNATAL', 'Postnatal support')], max_length=16)),
                ('result', models.CharField(choices=[('COMPLETED', 'Client met, visit completed'), ('ABSENT', 'Household reached, client absent'), ('MOVED', 'Household has moved away'), ('REFUSED', 'Client declined the visit'), ('NOT_REACHED', 'Household could not be reached')], max_length=12)),
                ('visit_date', models.DateField(db_index=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Support notes only. Do not record a clinical finding here. A clinical entry belongs to a supervisor.', max_length=1000)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_accuracy_metres', models.FloatField(blank=True, help_text='Accuracy radius the handset reported for the reading.', null=True)),
                ('location_captured_at', models.DateTimeField(blank=True, null=True)),
                ('location_status', models.CharField(choices=[('VERIFIED', 'Position matches the registered household'), ('OUT_OF_RANGE', 'Position is outside the match radius'), ('LOW_ACCURACY', 'Reading is too imprecise to judge'), ('NO_FIX', 'The handset obtained no position'), ('NO_REFERENCE', 'No household point is registered')], db_index=True, default='NO_FIX', max_length=14)),
                ('distance_from_household_metres', models.FloatField(blank=True, null=True)),
                ('location_verified_at', models.DateTimeField(blank=True, null=True)),
                ('flagged_for_review', models.BooleanField(db_index=True, default=False)),
                ('review_reason', models.CharField(blank=True, max_length=200)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_outcome', models.CharField(blank=True, help_text='What the supervisor found. An unverified visit is usually genuine.', max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_visits', to='registry.client')),
                ('infant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_visits', to='registry.infant')),
                ('mentor_mother', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_visits', to='registry.mentormother')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeospatialAnomaly',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=200)),
                ('kind', models.CharField(choices=[('IMPOSSIBLE_TRAVEL', 'Travel between visits was too fast'), ('IDENTICAL_POSITION', 'Several visits share one position'), ('CLUSTERED_DAY', 'A day of visits from a single point'), ('BULK_BACKDATED', 'Many records entered long after the date')], max_length=20)),
                ('detected_for_date', models.DateField(db_index=True)),
                ('detail', models.TextField(help_text='What the detection job measured.')),
                ('confidence', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=8)),
                ('disposition', models.CharField(choices=[('OPEN', 'Awaiting supervisor review'), ('EXPLAINED', 'Reviewed, an innocent explanation was found'), ('DATA_CORRECTED', 'Reviewed, the underlying data was wrong'), ('ESCALATED', 'Referred to the programme manager')], default='OPEN', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('mentor_mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='registry.mentormother')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_anomalies', to=settings.AUTH_USER_MODEL)),
                ('visits', models.ManyToManyField(blank=True, related_name='anomalies', to='visits.homevisit')),
            ],
            options={
                'verbose_name_plural': 'geospatial anomalies',
                'ordering': ['-detected_for_date'],
            },
        ),
        migrations.CreateModel(
            name='SyncBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=200)),
                ('device_id', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('ACCEPTED', 'All records accepted'), ('PARTIAL', 'Some records were rejected'), ('REJECTED', 'The batch was rejected')], max_length=10)),
                ('records_submitted', models.PositiveIntegerField(default=0)),
                ('records_accepted', models.PositiveIntegerField(default=0)),
                ('records_duplicate', models.PositiveIntegerField(default=0)),
                ('records_rejected', models.PositiveIntegerField(default=0)),
                ('rejection_detail', models.JSONField(blank=True, default=list)),
                ('oldest_record_created_at', models.DateTimeField(blank=True, null=True)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'sync batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='homevisit',
            index=models.Index(fields=['mentor_mother', 'visit_date'], name='visits_home_mentor__ec7aae_idx'),
        ),
        migrations.AddIndex(
            model_name='homevisit',
            index=models.Index(fields=['client', 'visit_date'], name='visits_home_client__3dfa6f_idx'),
        ),
        migrations.AddIndex(
            model_name='homevisit',
            index=models.Index(fields=['location_status', 'visit_date'], name='visits_home_locatio_15900d_idx'),
        ),
        migrations.AddConstraint(
            model_name='homevisit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitude__gte', -90), ('latitude__lte', 90)), ('latitude__isnull', True), _connector='OR'), name='visit_latitude_in_range'),
        ),
        migrations.AddConstraint(
            model_name='homevisit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('longitude__gte', -180), ('longitude__lte', 180)), ('longitude__isnull', True), _connector='OR'), name='visit_longitude_in_range'),
        ),
        migrations.AddIndex(
            model_name='geospatialanomaly',
            index=models.Index(fields=['mentor_mother', 'disposition'], name='visits_geos_mentor__06d46f_idx'),
        ),
    ]
